name: {{AGENT_NAME}} Auto-Merge

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, closed]
    branches:
      - '{{BASE_BRANCH}}'

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: |
      github.event.action != 'closed' &&
      (github.event.pull_request.user.login == '{{BOT_USERNAME}}' || 
      contains(github.event.pull_request.body, '[auto-merge]'))
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # CI: 動態偵測防護機制
      # 當 Phase 1 建出 backend 與 frontend 後，這些測試將自動硬性生效
      - name: Backend Tests (Maven)
        run: |
          if [ -f "./pom.xml" ]; then
            ./mvnw clean test
          elif [ -f "backend/pom.xml" ]; then
            cd backend && ./mvnw clean test
          else
            echo "Backend not initialized yet. Skipping tests."
          fi

      - name: Frontend Checks (NPM)
        run: |
          if [ -f "./package.json" ]; then
            npm install && npm run build
          elif [ -f "frontend/package.json" ]; then
            cd frontend && npm install && npm run build
          else
            echo "Frontend not initialized yet. Skipping checks."
          fi

      - name: Auto-merge PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
          token: ${{ secrets.GITHUB_TOKEN }}
