name: Phase Auto-Bump

# ðŸ”„ æ­¤ Workflow åœ¨ PR åˆä½µï¼ˆpush to mainï¼‰å¾Œè§¸ç™¼ï¼Œç¢ºä¿ Phase æŽ¨é€²ä¸æœƒèˆ‡ PR merge ç«¶çˆ­ã€‚

on:
  push:
    branches:
      - '{{BASE_BRANCH}}'
    paths:
      - '.{{AGENT_NAME}}/tracker.json'

permissions:
  contents: write

jobs:
  bump-phase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check and Bump Phase
        run: |
          TRACKER=".{{AGENT_NAME}}/tracker.json"

          if [ ! -f "$TRACKER" ]; then
            echo "No tracker found. Skipping."
            exit 0
          fi

          CURRENT_PHASE=$(jq -r '.current_phase' $TRACKER)
          echo "Current Phase: $CURRENT_PHASE"

          # æª¢æŸ¥ç•¶å‰ Phase æ˜¯å¦æ‰€æœ‰ä»»å‹™çš†å·² completed
          # âš ï¸ jq çš„ `all` å°ç©ºé™£åˆ—å›žå‚³ trueï¼Œå¿…é ˆå…ˆæª¢æŸ¥ length > 0
          ALL_DONE=$(jq -r --arg cp "$CURRENT_PHASE" '
            .phases[] | select(.name == $cp) | .tasks |
            if length > 0 then map(.status == "completed") | all else false end
          ' $TRACKER)

          if [ "$ALL_DONE" == "true" ]; then
            echo "All tasks in $CURRENT_PHASE are completed!"

            NEXT_PHASE=$(jq -r --arg cp "$CURRENT_PHASE" '
              (.phases | map(.name) | index($cp)) as $idx |
              if $idx != null and $idx + 1 < (.phases | length) then .phases[$idx + 1].name else "" end
            ' $TRACKER)

            if [ -n "$NEXT_PHASE" ]; then
              echo "Bumping phase to: $NEXT_PHASE"
              jq --arg np "$NEXT_PHASE" '.current_phase = $np' $TRACKER > tmp.json && mv tmp.json $TRACKER

              git config user.name "github-actions[bot]"
              git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
              git add $TRACKER
              git commit -m "chore: auto-bump phase to $NEXT_PHASE [skip ci]"
              git push
            else
              echo "ðŸŽ‰ All phases completed! Project is done."
            fi
          else
            echo "Phase $CURRENT_PHASE still has pending tasks."
          fi
